<a href="https://colab.research.google.com/github/charvimaini7/Financial-Forensics-Project/blob/main/Financial_Forensics_End_term_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import glob
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import drive

T1 Data Loading

In [ ]:
!unzip "FF.zip"

unzip:  cannot find or open FF.zip, FF.zip.zip or FF.zip.ZIP.

In [ ]:
# 1. Specify the path to your folder
folder_path = "/content/Financial Forensics/data/T1_data/"
# 2. Get a list of all CSV files in the folder
csv_files = glob.glob(folder_path + "*.csv")
# 3. Create an empty list to store the DataFrames
dfs = []
# 4. Loop through the files and read each one into a pandas DataFrame
for file in csv_files:
    df = pd.read_csv(file)
    dfs.append(df)
# 5. Access the loaded DataFrames
for i, df in enumerate(dfs):
    print(f"DataFrame {i+1}:")
    print(df.head())

Approach 1
filter stocks whose price has reduced from T1 to T2 then conduct a ratio analysis (in one the sheets we already have data regarding the ratios so you won't need to calculate from scratch)
For each ratio you'll need to identify if it's beneficial for the ratio to increase or decrease

The final list would be stocks whose prices have decreased but the ratios have improved and hence there's a buying opportunity

Ratios identified to be beneficial to increase:

* Dividend Yield
* Return on Assets
* Return on Equity

Ratios identified to be beneficial to decrease:
* Price to Earning (PE)
* Price to Book Value
* Debt to Equity

In [ ]:
# Load the two CSV files
price_file = "price.csv"  # Replace with the path to your first file
price_T2_file = "price_T2.csv"  # Replace with the path to your second file

price_df = pd.read_csv(price_file)
price_T2_df = pd.read_csv(price_T2_file)

# Merge the two DataFrames on the stock identifier (assuming the column is called 'Stock')
merged_data = pd.merge(price_df, price_T2_df, on='Name', suffixes=('_T1', '_T2'))

# Filter stocks where the price has reduced
price_reduced_stocks = merged_data[merged_data['Current Price_T2'] < merged_data['Current Price_T1']]

# Save the filtered stocks to a new CSV file
output_file = "stocks_with_reduced_price.csv"
price_reduced_stocks.to_csv(output_file, index=False)

# Print the result and show the filtered stocks
print(f"Filtered {len(price_reduced_stocks)} stocks where the price has reduced.")
display(price_reduced_stocks)

Filtered 1928 stocks where the price has reduced.

,Name,BSE Code_T1,NSE Code_T1,Industry_T1,Current Price_T1,Return over 3months_T1,Return over 6months_T1,Volume 1month average_T1,Volume 1week average_T1,Volume_T1,...,MACD Previous Day_T2,MACD Signal_T2,MACD Signal Previous Day_T2,Return over 1year_T2,Return over 3years_T2,Return over 5years_T2,Volume 1year average_T2,Return over 7years_T2,Return over 10years_T2,Market Capitalization_T2
4,3C IT Solutions,544190.0,NaN,Computers - Software - Medium / Small,45.00,NaN,NaN,159500,81000,74000,...,-1.32,-1.59,-1.68,NaN,NaN,NaN,91200,NaN,NaN,23.66
5,3i Infotech,532628.0,3IINFOLTD,Computers - Software - Medium / Small,36.52,-14.51,-34.37,2154301,1374227,1711540,...,-0.22,-0.10,-0.04,4.82,58.28,73.81,2334827,36.22,14.58,604.10
7,3P Land Hold.,516092.0,3PLAND,Finance & Investments,38.00,29.48,37.35,52715,173461,307633,...,0.78,0.93,0.98,92.01,34.67,37.07,41223,18.28,11.57,67.05
8,52 Weeks Enter.,531925.0,NaN,Entertainment / Electronic Media Software,1.69,0.62,8.00,73418,32989,30856,...,-0.01,-0.02,-0.02,25.60,-18.96,20.04,44280,-42.70,-24.62,5.48
9,5Paisa Capital,540776.0,5PAISA,Finance & Investments,514.30,-4.98,-24.93,56967,66172,30693,...,-6.93,-8.38,-8.85,8.41,-0.69,27.55,138587,NaN,NaN,1516.79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4603,Zodiac Cloth. Co,521163.0,ZODIACLOTH,Textiles - Products,142.45,24.37,17.24,340436,891732,65573,...,-0.76,0.20,0.52,10.75,-0.87,-8.31,90297,-5.72,-10.54,338.83
4604,Zodiac Energy,543416.0,ZODIAC,Engineering - Turnkey Services,773.45,84.12,222.86,21724,37809,43487,...,10.80,10.81,10.35,502.05,247.30,128.64,35610,NaN,NaN,1099.31
4605,Zodiac Vent.,503641.0,NaN,Construction,16.19,17.50,-4.37,305753,254935,185355,...,-0.14,-0.12,-0.11,-10.37,-12.31,-13.86,101032,NaN,-11.59,54.82
4609,Zuari Agro Chem.,534742.0,ZUARI,Fertilizers,227.55,16.52,11.97,730821,528719,680308,...,2.19,2.46,2.44,40.58,14.65,14.22,471888,-7.24,2.28,933.31
4610,Zuari Industries,500780.0,ZUARIIND,Sugar,409.70,18.79,94.90,389973,515426,1184233,...,5.38,6.58,7.15,140.33,35.10,38.36,252500,15.78,15.75,1113.67

In [ ]:
# Load the two CSV files
ratio_file = "ratios_1.csv"  # Replace with the path to your first file
ratio_2_file = "ratios_1_T2.csv"  # Replace with the path to your second file

ratio_df = pd.read_csv(ratio_file)
ratio_2_df = pd.read_csv(ratio_2_file)

# Merge the two DataFrames on a common identifier, e.g., 'Stock'
merged_data = pd.merge(ratio_df, ratio_2_df, on='Name', suffixes=('_T1', '_T2'))

# Filter rows where the specified columns have increased
increased_ratios = merged_data[
    (merged_data['Dividend yield_T2'] > merged_data['Dividend yield_T1']) &
    (merged_data['Return on assets_T2'] > merged_data['Return on assets_T1']) &
    (merged_data['Return on equity_T2'] > merged_data['Return on equity_T1'])
]

# Save the filtered stocks to a new CSV file
output_file = "increased_ratios.csv"
increased_ratios.to_csv(output_file, index=False)

# Print the result and display the filtered rows
print(f"Filtered {len(increased_ratios)} stocks where ratios have increased.")
display(increased_ratios)

Filtered 51 stocks where ratios have increased.

,Name,BSE Code_T1,NSE Code_T1,Industry_T1,Current Price_T1,Market Capitalization_T1,Price to Earning_T1,Dividend yield_T1,Price to book value_T1,Return on assets_T1,...,Public holding_T2,FII holding_T2,Change in FII holding_T2,DII holding_T2,Change in DII holding_T2,Book value preceding year_T2,Return on capital employed preceding year_T2,Return on assets preceding year_T2,Return on equity preceding year_T2,Number of Shareholders preceding quarter_T2
105,Aditya Vision,540205.0,NaN,Trading,4498.95,5788.47,75.12,0.15,11.86,10.32,...,28.31,10.23,0.81,8.23,0.74,113.31,25.24,12.34,59.61,11038.0
117,Advanced Enzyme,540025.0,ADVENZYMES,Pharmaceuticals - Indian - Bulk Drugs & Formln,378.95,4237.61,29.50,1.06,3.20,10.02,...,36.87,12.03,-10.98,8.08,0.52,110.45,11.93,8.03,9.23,68640.0
330,Arvind Fashions.,542484.0,ARVINDFASN,Trading,518.65,6908.49,102.20,0.18,6.87,3.16,...,37.27,15.58,-0.15,11.93,1.27,68.50,13.78,2.55,4.51,168919.0
510,Bayer Crop Sci.,506285.0,BAYERCROP,Pesticides / Agrochemicals - Multinational,6899.45,31007.61,41.88,1.92,10.90,15.97,...,12.47,3.63,0.01,12.47,-0.33,603.47,33.66,15.02,25.91,45852.0
594,Birla Corpn.,500335.0,BIRLACORPN,Cement - North India,1600.35,12324.28,29.68,0.16,1.84,2.91,...,14.84,5.99,-0.80,16.26,0.66,776.67,3.73,0.31,0.73,111096.0
639,Bosch,500530.0,BOSCHLTD,Auto Ancillaries,34280.25,101104.93,55.28,1.09,8.37,10.89,...,7.71,5.96,1.86,15.80,-1.39,3733.76,17.39,9.01,13.15,65376.0
648,Brigade Enterpr.,532929.0,BRIGADE,Construction,1360.15,31437.93,78.34,0.15,8.64,2.34,...,17.26,16.17,1.31,22.86,-0.98,140.64,8.41,1.24,6.34,76977.0
710,CEAT,500878.0,CEATLTD,Tyres,2851.10,11532.71,17.05,0.43,2.82,6.91,...,16.92,18.76,-1.40,17.09,1.18,850.34,9.38,2.19,6.14,114397.0
724,Centum Electron,517544.0,CENTUM,Electronics - Components,1649.00,2126.70,NaN,0.23,10.45,-0.74,...,32.76,0.37,0.00,8.13,0.44,163.54,7.65,0.67,3.23,23497.0
1086,Eicher Motors,505200.0,EICHERMOT,Automobiles - Motorcycles / Mopeds,4677.00,128154.73,32.03,0.78,7.10,18.91,...,10.14,28.81,-0.14,11.84,0.80,548.13,27.35,16.49,21.12,263132.0
1089,EIH,500840.0,EIHOTEL,Hotels,422.20,26402.91,40.96,0.27,6.69,14.47,...,48.08,5.39,0.14,13.67,-0.10,53.96,15.61,8.92,11.37,120423.0
1104,Electrost.Cast.,500128.0,ELECTCAST,Castings & Forgings,176.70,10506.71,14.27,0.51,2.06,8.40,...,31.95,21.16,1.46,0.44,0.08,73.29,10.01,3.73,7.54,121615.0
1463,Greaves Cotton,501455.0,GREAVESCOT,Engines,135.00,3136.52,NaN,0.68,2.15,-5.12,...,39.18,1.15,-1.66,3.76,0.01,68.49,9.09,3.54,6.59,205042.0
1493,Guj Pipavav Port,533248.0,GPPL,Miscellaneous,211.55,10227.15,26.93,2.87,4.44,13.08,...,20.42,18.53,0.22,17.04,-0.34,47.80,19.60,12.18,14.99,215960.0
1528,H.G. Infra Engg.,541019.0,HGINFRA,Construction,1745.75,11377.24,21.64,0.07,4.64,10.17,...,11.30,2.04,0.36,12.13,-0.37,294.90,25.36,12.04,29.36,85596.0
1617,Hindalco Inds.,500440.0,HINDALCO,Aluminium and Aluminium Products,694.55,156080.38,15.40,0.43,1.49,4.45,...,11.98,27.18,0.36,25.41,-0.23,421.89,11.34,4.53,11.67,641541.0
1690,IKIO Lighting,543923.0,IKIO,Electric Equipment,300.35,2321.12,38.32,0.00,4.19,12.51,...,21.68,0.71,-0.85,5.12,0.17,NaN,30.59,17.38,39.86,124136.0
1707,Indag Rubber,509162.0,NaN,Miscellaneous,243.80,639.99,38.23,0.97,2.80,6.52,...,26.01,0.64,-0.36,0.00,0.00,80.69,8.34,5.46,6.33,7790.0
1742,Indian Toners,523586.0,NaN,Dyes And Pigments,309.70,335.99,12.86,1.44,1.60,11.76,...,30.72,0.00,0.00,0.03,0.00,173.51,19.53,13.06,14.87,16558.0
1753,Indo Count Inds.,521016.0,ICIL,Textiles - Cotton/Blended,440.00,8714.41,25.80,0.47,4.18,10.20,...,28.40,10.69,-0.05,2.16,1.10,90.52,15.07,8.76,16.33,73384.0
1780,InfoBeans Tech.,543644.0,INFOBEAN,Computers - Software - Medium / Small,452.40,1102.44,49.06,0.22,3.72,5.54,...,25.72,0.29,0.00,0.01,0.00,111.97,19.11,8.96,14.32,28397.0
1945,JK Tyre & Indust,530007.0,JKTYRE,Tyres,442.20,11529.17,14.32,0.43,2.58,6.24,...,27.73,14.15,-1.14,4.99,-0.19,137.93,11.13,2.42,9.49,226143.0
1955,Joindre Capital,531861.0,NaN,Finance & Investments,51.00,70.58,46.43,2.45,0.98,1.06,...,36.32,0.00,0.00,0.00,0.00,51.85,6.56,2.52,4.35,3742.0
1966,JSW Steel,500228.0,JSWSTEEL,Steel - Large,943.20,230655.22,27.35,0.78,2.99,3.91,...,18.30,25.52,-0.54,10.52,0.71,271.78,8.33,1.84,5.64,671779.0
2024,Kamdhenu,532741.0,KAMDHENU,Steel - Medium / Small,521.50,1404.69,28.02,0.29,6.58,20.35,...,36.65,6.12,2.12,0.18,-0.01,61.96,23.22,12.25,20.94,17169.0
2157,Kovai Medical,523323.0,NaN,Healthcare,4289.75,4693.00,26.11,0.12,5.27,12.48,...,38.91,0.32,-0.02,4.28,0.10,657.12,16.79,8.44,17.67,11918.0
2303,M R P L,500109.0,MRPL,Refineries,215.55,37777.26,10.52,0.47,2.86,10.21,...,7.64,2.26,-0.42,1.50,0.00,56.29,20.13,7.08,31.22,440569.0
2326,Mafatlal Inds.,500264.0,NaN,Textiles - Composite,208.30,1496.71,15.15,0.00,1.86,1.70,...,28.75,0.71,-0.14,0.93,-0.01,86.89,5.25,1.70,3.13,60676.0
2328,Magadh Sugar,540650.0,MAGADSUGAR,Sugar,771.00,1086.45,9.31,0.90,1.46,7.71,...,38.55,0.43,-0.06,0.01,0.00,453.72,8.76,3.65,8.14,11180.0
2501,Minda Corp,538962.0,MINDACORP,Auto Ancillaries,487.50,11655.12,51.26,0.24,5.87,6.84,...,6.86,6.07,1.00,20.63,0.03,66.34,16.47,9.86,19.56,100689.0
2534,Modison,506261.0,MODISONLTD,Electric Equipment,124.25,403.19,23.40,0.80,1.97,7.00,...,47.40,0.48,0.07,0.00,0.00,57.65,10.24,5.91,7.09,19040.0
2556,Morganite Crucib,523160.0,NaN,Refractories / Intermediates,1510.00,845.60,32.86,1.83,6.60,15.35,...,24.32,0.13,0.13,0.55,0.53,226.70,17.84,10.17,12.88,6270.0
2609,N R Agarwal Inds,516082.0,NRAIL,Paper,505.20,859.80,6.86,0.00,1.13,9.62,...,25.56,0.46,0.05,0.01,0.00,373.48,21.55,9.79,17.09,9725.0
2918,Patels Airtemp,517417.0,NaN,Engineering,728.00,398.23,27.12,0.41,2.78,4.02,...,53.57,0.00,0.00,0.00,0.00,236.85,12.93,3.46,9.29,7195.0
2968,Pidilite Inds.,500331.0,PIDILITIND,Chemicals,3163.75,160911.28,90.35,0.35,19.14,15.92,...,9.71,11.59,0.28,8.97,0.04,141.89,23.83,12.89,18.70,541114.0
3370,S H Kelkar & Co.,539450.0,SHK,Chemicals,192.35,2662.50,21.70,1.04,2.20,5.37,...,32.27,8.71,-0.15,0.27,0.00,76.89,8.04,3.18,6.66,46379.0
3497,Saurashtra Cem.,502175.0,SAURASHCEM,Cement - North India,134.25,1489.97,21.45,0.74,1.63,4.74,...,32.73,0.01,0.01,0.37,0.00,125.35,-1.97,-1.55,-2.40,52990.0
3619,Shilchar Tech.,531201.0,NaN,Electric Equipment,5797.20,4421.41,48.12,0.09,21.09,39.08,...,32.37,3.08,-0.47,0.02,0.02,159.79,53.97,26.70,42.96,16011.0
3643,Shree Cement,500387.0,SHREECEM,Cement - North India,28214.80,101801.12,42.49,0.36,4.95,8.83,...,12.59,11.85,-0.62,12.78,0.64,5165.20,8.51,5.03,6.98,28268.0
3737,Siyaram Silk,503811.0,SIYSIL,Textiles - Processing,516.65,2344.05,12.70,2.12,2.06,11.38,...,28.47,1.53,-0.03,2.54,-0.39,243.42,28.12,15.73,23.88,39722.0
3766,Sobha,532784.0,SOBHA,Construction,1963.45,20999.84,427.64,0.15,8.34,0.37,...,17.24,10.93,-0.94,19.04,1.49,233.15,8.32,0.86,4.24,100295.0
3932,Sunshield Chem.,530845.0,NaN,Chemicals,1020.20,750.16,39.83,0.20,9.15,9.27,...,32.60,5.01,0.00,0.01,0.00,89.76,19.26,7.79,22.83,4617.0
4004,Swelect Energy,532051.0,SWELECTES,Electric Equipment,1265.00,1917.59,79.13,0.24,2.28,1.57,...,43.32,0.12,0.06,0.20,-0.27,519.32,4.16,0.13,0.21,23905.0
4041,TajGVK Hotels,532390.0,TAJGVK,Hotels,335.20,2101.79,28.24,0.00,3.86,9.40,...,21.49,0.82,0.12,2.69,-0.27,73.57,22.49,12.76,22.50,77579.0
4088,TD Power Systems,533553.0,TDPOWERSYS,Electric Equipment,353.45,5520.32,46.64,0.14,7.85,12.19,...,19.34,14.84,1.99,31.53,-0.83,38.74,22.06,10.59,16.93,68416.0
4130,Thermax,500411.0,THERMAX,Engineering,5323.80,63436.45,108.02,0.22,14.28,6.19,...,4.50,15.15,2.91,12.88,-2.94,324.62,15.06,5.57,12.31,40819.0
4152,Tinna Rubber,530475.0,NaN,Miscellaneous,1873.15,3208.61,79.64,0.16,25.11,17.49,...,26.22,0.79,0.05,0.00,0.00,56.13,23.57,11.08,24.39,21711.0
4223,Tube Investments,540762.0,TIINDIA,Steel - Large,4213.30,81491.91,98.54,0.08,15.97,10.14,...,11.61,27.40,-0.93,15.49,0.69,204.56,31.58,13.72,26.97,80778.0
4314,UTI AMC,543238.0,UTIAMC,Finance & Investments,1033.10,13149.27,17.19,2.15,2.99,16.86,...,33.08,6.27,0.30,60.67,-0.26,304.59,15.88,10.78,11.68,148066.0
4514,Weizmann,523011.0,WEIZMANIND,Textiles - Processing,134.80,213.79,23.84,0.37,2.95,9.01,...,32.13,0.00,0.00,0.00,0.00,40.82,12.34,4.10,6.61,9612.0
4554,WPIL,505872.0,NaN,Engineering - Turnkey Services,4436.00,4332.69,32.32,0.48,3.47,8.03,...,20.78,5.81,-0.01,2.62,0.00,82.89,24.33,10.99,26.25,12803.0

In [ ]:
# Load the two CSV files
ratio_file = "ratios_1.csv"  # Replace with the path to your first file
ratio_2_file = "ratios_1_T2.csv"  # Replace with the path to your second file

ratio_df = pd.read_csv(ratio_file)
ratio_2_df = pd.read_csv(ratio_2_file)

# Merge the two DataFrames on a common identifier, e.g., 'Stock'
merged_data = pd.merge(ratio_df, ratio_2_df, on='Name', suffixes=('_T1', '_T2'))

# Filter rows where:
# 1. Price has reduced
# 2. PE, PBV, and Debt to Equity have decreased
filtered_data = merged_data[
    (merged_data['Price to Earning_T2'] < merged_data['Price to Earning_T1']) &
    (merged_data['Price to book value_T2'] < merged_data['Price to book value_T1']) &
    (merged_data['Debt to equity_T2'] < merged_data['Debt to equity_T1'])
]

# Save the filtered stocks to a new CSV file
output_file = "decreased_ratios.csv"
filtered_data.to_csv(output_file, index=False)

# Print the result and display the filtered rows
print(f"Filtered {len(filtered_data)} stocks where ratios improved.")
display(filtered_data)

Filtered 8 stocks where ratios improved.

,Name,BSE Code_T1,NSE Code_T1,Industry_T1,Current Price_T1,Market Capitalization_T1,Price to Earning_T1,Dividend yield_T1,Price to book value_T1,Return on assets_T1,...,Public holding_T2,FII holding_T2,Change in FII holding_T2,DII holding_T2,Change in DII holding_T2,Book value preceding year_T2,Return on capital employed preceding year_T2,Return on assets preceding year_T2,Return on equity preceding year_T2,Number of Shareholders preceding quarter_T2
124,Aether Industri.,543534.0,AETHER,Chemicals,921.90,12219.81,131.60,0.00,5.95,4.91,...,3.74,2.90,0.68,11.55,-0.27,99.96,18.44,12.07,15.91,78655.0
432,Axis Bank,532215.0,AXISBANK,Banks - Private Sector,1266.30,391292.34,14.86,0.08,3.01,1.97,...,6.63,53.43,-0.41,31.63,1.51,421.80,5.12,0.86,8.73,786166.0
774,CIE Automotive,532756.0,CIEINDIA,Castings & Forgings,596.45,22627.06,28.02,0.84,3.82,11.44,...,9.78,5.03,-0.08,19.45,1.33,134.41,14.65,-0.86,-1.65,134185.0
791,City Union Bank,532210.0,CUB,Banks - Private Sector,167.50,12406.28,12.22,0.60,1.67,1.53,...,41.00,26.44,-0.51,32.55,3.05,100.72,6.01,1.46,13.35,248815.0
1567,HDFC Bank,500180.0,HDFCBANK,Banks - Private Sector,1696.60,1290794.05,20.15,1.16,3.28,2.59,...,17.44,47.17,-0.66,35.20,1.87,518.73,6.24,1.98,17.11,4121815.0
1862,J & K Bank,532209.0,J&KBANK,Banks - Private Sector,115.75,12746.16,7.22,0.42,1.20,1.21,...,26.70,7.16,0.17,6.74,-1.16,95.94,4.92,0.85,13.13,215294.0
4100,Teesta Agro Ind.,524204.0,NaN,Fertilizers,119.00,66.78,21.54,0.00,0.60,1.67,...,51.99,0.00,0.00,3.75,0.00,191.02,9.46,4.25,7.04,14186.0
4267,Union Bank (I),532477.0,UNIONBANK,Banks - Public Sector,135.20,103206.35,7.48,2.65,1.19,1.07,...,6.50,7.37,0.62,11.38,-0.86,115.30,5.02,0.69,11.38,914940.0

In [ ]:
# Load the three CSV files
reduced_price_file = "stocks_with_reduced_price.csv"  # Replace with the path to your reduced price file
increased_ratios_file = "increased_ratios.csv"       # Replace with the path to your increased ratios file
decreased_ratios_file = "decreased_ratios.csv"       # Replace with the path to your decreased ratios file

reduced_price_df = pd.read_csv(reduced_price_file)
increased_ratios_df = pd.read_csv(increased_ratios_file)
decreased_ratios_df = pd.read_csv(decreased_ratios_file)

# Merge the DataFrames on the 'Name' column (or 'Stock' depending on your data)
merged_data = reduced_price_df.merge(increased_ratios_df, on='Name', how='inner')
merged_data = merged_data.merge(decreased_ratios_df, on='Name', how='inner')

# Save the final filtered list to a new CSV file
output_file = "picked_stocks.csv"
merged_data.to_csv(output_file, index=False)

# Print the result and display the filtered rows
print(f"Filtered {len(merged_data)} stocks that exist in all three files.")
display(merged_data)

Filtered 0 stocks that exist in all three files.

Empty DataFrame
Columns: [Name, BSE Code_T1_x, NSE Code_T1_x, Industry_T1_x, Current Price_T1_x, Return over 3months_T1, Return over 6months_T1, Volume 1month average_T1, Volume 1week average_T1, Volume_T1, High price_T1, Low price_T1, High price all time_T1, Low price all time_T1, Return over 1day_T1, Return over 1week_T1, Return over 1month_T1, DMA 50_T1, DMA 200_T1, DMA 50 previous day_T1, DMA 200 previous day_T1, RSI_T1, MACD_T1, MACD Previous Day_T1, MACD Signal_T1, MACD Signal Previous Day_T1, Return over 1year_T1, Return over 3years_T1, Return over 5years_T1, Volume 1year average_T1, Return over 7years_T1, Return over 10years_T1, Market Capitalization_T1_x, BSE Code_T2_x, NSE Code_T2_x, Industry_T2_x, Current Price_T2_x, Return over 3months_T2, Return over 6months_T2, Volume 1month average_T2, Volume 1week average_T2, Volume_T2, High price_T2, Low price_T2, High price all time_T2, Low price all time_T2, Return over 1day_T2, Return over 1week_T2, Return over 1month_T2, DMA 50_T2, DMA 200_T2, DMA 50 previous day_T2, DMA 200 previous day_T2, RSI_T2, MACD_T2, MACD Previous Day_T2, MACD Signal_T2, MACD Signal Previous Day_T2, Return over 1year_T2, Return over 3years_T2, Return over 5years_T2, Volume 1year average_T2, Return over 7years_T2, Return over 10years_T2, Market Capitalization_T2_x, BSE Code_T1_y, NSE Code_T1_y, Industry_T1_y, Current Price_T1_y, Market Capitalization_T1_y, Price to Earning_T1_x, Dividend yield_T1_x, Price to book value_T1_x, Return on assets_T1_x, Debt to equity_T1_x, Return on equity_T1_x, Promoter holding_T1_x, Earnings yield_T1_x, Pledged percentage_T1_x, Industry PE_T1_x, Enterprise Value_T1_x, Number of equity shares_T1_x, Book value_T1_x, Inventory turnover ratio_T1_x, Quick ratio_T1_x, Exports percentage_T1_x, Piotroski score_T1_x, G Factor_T1_x, Asset Turnover Ratio_T1_x, Financial leverage_T1_x, Number of Shareholders_T1_x, Unpledged promoter holding_T1_x, Return on invested capital_T1_x, Debtor days_T1_x, Industry PBV_T1_x, Credit rating_T1_x, Working Capital Days_T1_x, Earning Power_T1_x, Graham Number_T1_x, Cash Conversion Cycle_T1_x, ...]
Index: []

[0 rows x 257 columns]

In [ ]:
import pandas as pd

# Load the necessary CSV files
price_file = "price.csv"  # File with price data for T1
price_T2_file = "price_T2.csv"  # File with price data for T2
ratio_file = "ratios_1.csv"  # File with ratio data for T1
ratio_T2_file = "ratios_1_T2.csv"  # File with ratio data for T2

# Load the data
price_df = pd.read_csv(price_file)
price_T2_df = pd.read_csv(price_T2_file)
ratio_df = pd.read_csv(ratio_file)
ratio_T2_df = pd.read_csv(ratio_T2_file)

# Merge price data to compare the current price from T1 and T2
merged_price_data = pd.merge(price_df, price_T2_df, on='Name', suffixes=('_T1', '_T2'))

# Filter for stocks where the price has decreased
reduced_price_stocks = merged_price_data[merged_price_data['Current Price_T1'] > merged_price_data['Current Price_T2']]

# Merge ratio data
merged_ratio_data = pd.merge(ratio_df, ratio_T2_df, on='Name', suffixes=('_T1', '_T2'))

# Filter for stocks where ratios have improved
improved_ratios = merged_ratio_data[
    (merged_ratio_data['Dividend yield_T2'] > merged_ratio_data['Dividend yield_T1']) &
    (merged_ratio_data['Return on assets_T2'] > merged_ratio_data['Return on assets_T1']) &
    (merged_ratio_data['Return on equity_T2'] > merged_ratio_data['Return on equity_T1']) &
    (merged_ratio_data['Price to Earning_T2'] < merged_ratio_data['Price to Earning_T1']) &
    (merged_ratio_data['Price to book value_T2'] < merged_ratio_data['Price to book value_T1']) &
    (merged_ratio_data['Debt to equity_T2'] < merged_ratio_data['Debt to equity_T1'])
]

# Merge the reduced price stocks and improved ratios to find stocks that meet both criteria
final_stocks = pd.merge(reduced_price_stocks, improved_ratios, on='Name')

# Save the result to a new CSV
final_stocks.to_csv("stocks_with_reduced_price_and_improved_ratios.csv", index=False)

# Print the result
print(f"Filtered {len(final_stocks)} stocks that have reduced prices and improved ratios.")

Filtered 0 stocks that have reduced prices and improved ratios.

Approach 2 - filter stocks whose price has increased from T1 to T2 and then conduct the same ratio analysis as above

In [ ]:
# Load the two CSV files
price_file = "price.csv"  # Replace with the path to your first file
price_T2_file = "price_T2.csv"  # Replace with the path to your second file

price_df = pd.read_csv(price_file)
price_T2_df = pd.read_csv(price_T2_file)

# Merge the two DataFrames on the stock identifier (assuming the column is called 'Stock')
merged_data = pd.merge(price_df, price_T2_df, on='Name', suffixes=('_T1', '_T2'))

# Filter stocks where the price has reduced
price_increased_stocks = merged_data[merged_data['Current Price_T2'] > merged_data['Current Price_T1']]

# Save the filtered stocks to a new CSV file
output_file = "stocks_with_increased_price.csv"
price_increased_stocks.to_csv(output_file, index=False)

# Print the result and show the filtered stocks
print(f"Filtered {len(price_increased_stocks)} stocks where the price has increased.")
display(price_increased_stocks)

Filtered 2662 stocks where the price has increased.

,Name,BSE Code_T1,NSE Code_T1,Industry_T1,Current Price_T1,Return over 3months_T1,Return over 6months_T1,Volume 1month average_T1,Volume 1week average_T1,Volume_T1,...,MACD Previous Day_T2,MACD Signal_T2,MACD Signal Previous Day_T2,Return over 1year_T2,Return over 3years_T2,Return over 5years_T2,Volume 1year average_T2,Return over 7years_T2,Return over 10years_T2,Market Capitalization_T2
0,20 Microns,533022.0,20MICRONS,Mining / Minerals / Metals,225.20,44.62,23.16,729846,816052,312746,...,16.51,13.18,11.84,167.43,65.26,54.21,285837,34.20,24.92,1015.37
1,21st Cent. Mgmt.,526921.0,21STCENMGM,Finance & Investments,70.44,54.12,114.43,34120,27069,11745,...,4.79,4.96,4.95,320.98,52.47,43.87,14469,20.42,27.06,90.62
2,360 ONE,542772.0,360ONE,Finance & Investments,995.85,40.86,49.58,1193124,2871837,5329590,...,53.32,46.19,45.12,108.01,40.13,NaN,758179,NaN,NaN,38329.62
3,3B Blackbio,532067.0,NaN,Healthcare,1184.50,48.07,25.94,21265,5355,7221,...,28.49,20.08,16.38,154.37,26.49,69.93,13972,58.03,62.20,1069.10
6,3M India,523395.0,3MINDIA,Diversified - Large,37310.00,21.56,7.50,9903,6461,7417,...,594.53,664.47,680.28,39.93,17.31,13.60,6872,16.82,22.01,44418.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4606,Zodiac-JRD MKJ,512587.0,NaN,Diamond Cutting / Jewellery,64.84,-5.54,7.94,8697,16006,37509,...,1.14,0.32,-0.11,114.69,35.29,25.82,14774,8.08,9.85,42.39
4607,Zomato Ltd,543320.0,ZOMATO,Miscellaneous,199.35,9.54,57.24,49726980,45162489,40913151,...,7.69,7.89,7.32,174.99,24.80,NaN,67156536,NaN,NaN,231567.13
4608,Zota Health Care,NaN,ZOTA,Trading,571.00,14.38,17.99,145025,47535,24594,...,14.58,12.51,10.34,70.79,24.93,28.17,55402,32.81,NaN,1832.86
4611,Zydus Lifesci.,532321.0,ZYDUSLIFE,Pharmaceuticals - Indian - Bulk Drugs & Formln,1066.50,8.16,51.18,1576433,1664357,2401384,...,35.90,32.71,31.65,92.37,28.83,40.75,1457897,12.95,18.99,125769.19
4612,Zydus Wellness,531335.0,ZYDUSWELL,Food - Processing - Indian,1854.00,19.07,5.71,47180,20245,28152,...,118.82,114.14,116.00,58.04,0.16,8.31,56443,14.34,13.92,14387.86

In [ ]:
# Load the two CSV files
ratio_file = "ratios_1.csv"  # Replace with the path to your first file
ratio_2_file = "ratios_1_T2.csv"  # Replace with the path to your second file

ratio_df = pd.read_csv(ratio_file)
ratio_2_df = pd.read_csv(ratio_2_file)

# Merge the two DataFrames on a common identifier, e.g., 'Stock'
merged_data = pd.merge(ratio_df, ratio_2_df, on='Name', suffixes=('_T1', '_T2'))

# Filter rows where the specified columns have increased
increased_ratios = merged_data[
    (merged_data['Dividend yield_T2'] > merged_data['Dividend yield_T1']) &
    (merged_data['Return on assets_T2'] > merged_data['Return on assets_T1']) &
    (merged_data['Return on equity_T2'] > merged_data['Return on equity_T1'])
]

# Save the filtered stocks to a new CSV file
output_file = "increased_ratios_approach2.csv"
increased_ratios.to_csv(output_file, index=False)

# Print the result and display the filtered rows
print(f"Filtered {len(increased_ratios)} stocks where ratios have increased.")
display(increased_ratios)

Filtered 51 stocks where ratios have increased.

,Name,BSE Code_T1,NSE Code_T1,Industry_T1,Current Price_T1,Market Capitalization_T1,Price to Earning_T1,Dividend yield_T1,Price to book value_T1,Return on assets_T1,...,Public holding_T2,FII holding_T2,Change in FII holding_T2,DII holding_T2,Change in DII holding_T2,Book value preceding year_T2,Return on capital employed preceding year_T2,Return on assets preceding year_T2,Return on equity preceding year_T2,Number of Shareholders preceding quarter_T2
105,Aditya Vision,540205.0,NaN,Trading,4498.95,5788.47,75.12,0.15,11.86,10.32,...,28.31,10.23,0.81,8.23,0.74,113.31,25.24,12.34,59.61,11038.0
117,Advanced Enzyme,540025.0,ADVENZYMES,Pharmaceuticals - Indian - Bulk Drugs & Formln,378.95,4237.61,29.50,1.06,3.20,10.02,...,36.87,12.03,-10.98,8.08,0.52,110.45,11.93,8.03,9.23,68640.0
330,Arvind Fashions.,542484.0,ARVINDFASN,Trading,518.65,6908.49,102.20,0.18,6.87,3.16,...,37.27,15.58,-0.15,11.93,1.27,68.50,13.78,2.55,4.51,168919.0
510,Bayer Crop Sci.,506285.0,BAYERCROP,Pesticides / Agrochemicals - Multinational,6899.45,31007.61,41.88,1.92,10.90,15.97,...,12.47,3.63,0.01,12.47,-0.33,603.47,33.66,15.02,25.91,45852.0
594,Birla Corpn.,500335.0,BIRLACORPN,Cement - North India,1600.35,12324.28,29.68,0.16,1.84,2.91,...,14.84,5.99,-0.80,16.26,0.66,776.67,3.73,0.31,0.73,111096.0
639,Bosch,500530.0,BOSCHLTD,Auto Ancillaries,34280.25,101104.93,55.28,1.09,8.37,10.89,...,7.71,5.96,1.86,15.80,-1.39,3733.76,17.39,9.01,13.15,65376.0
648,Brigade Enterpr.,532929.0,BRIGADE,Construction,1360.15,31437.93,78.34,0.15,8.64,2.34,...,17.26,16.17,1.31,22.86,-0.98,140.64,8.41,1.24,6.34,76977.0
710,CEAT,500878.0,CEATLTD,Tyres,2851.10,11532.71,17.05,0.43,2.82,6.91,...,16.92,18.76,-1.40,17.09,1.18,850.34,9.38,2.19,6.14,114397.0
724,Centum Electron,517544.0,CENTUM,Electronics - Components,1649.00,2126.70,NaN,0.23,10.45,-0.74,...,32.76,0.37,0.00,8.13,0.44,163.54,7.65,0.67,3.23,23497.0
1086,Eicher Motors,505200.0,EICHERMOT,Automobiles - Motorcycles / Mopeds,4677.00,128154.73,32.03,0.78,7.10,18.91,...,10.14,28.81,-0.14,11.84,0.80,548.13,27.35,16.49,21.12,263132.0
1089,EIH,500840.0,EIHOTEL,Hotels,422.20,26402.91,40.96,0.27,6.69,14.47,...,48.08,5.39,0.14,13.67,-0.10,53.96,15.61,8.92,11.37,120423.0
1104,Electrost.Cast.,500128.0,ELECTCAST,Castings & Forgings,176.70,10506.71,14.27,0.51,2.06,8.40,...,31.95,21.16,1.46,0.44,0.08,73.29,10.01,3.73,7.54,121615.0
1463,Greaves Cotton,501455.0,GREAVESCOT,Engines,135.00,3136.52,NaN,0.68,2.15,-5.12,...,39.18,1.15,-1.66,3.76,0.01,68.49,9.09,3.54,6.59,205042.0
1493,Guj Pipavav Port,533248.0,GPPL,Miscellaneous,211.55,10227.15,26.93,2.87,4.44,13.08,...,20.42,18.53,0.22,17.04,-0.34,47.80,19.60,12.18,14.99,215960.0
1528,H.G. Infra Engg.,541019.0,HGINFRA,Construction,1745.75,11377.24,21.64,0.07,4.64,10.17,...,11.30,2.04,0.36,12.13,-0.37,294.90,25.36,12.04,29.36,85596.0
1617,Hindalco Inds.,500440.0,HINDALCO,Aluminium and Aluminium Products,694.55,156080.38,15.40,0.43,1.49,4.45,...,11.98,27.18,0.36,25.41,-0.23,421.89,11.34,4.53,11.67,641541.0
1690,IKIO Lighting,543923.0,IKIO,Electric Equipment,300.35,2321.12,38.32,0.00,4.19,12.51,...,21.68,0.71,-0.85,5.12,0.17,NaN,30.59,17.38,39.86,124136.0
1707,Indag Rubber,509162.0,NaN,Miscellaneous,243.80,639.99,38.23,0.97,2.80,6.52,...,26.01,0.64,-0.36,0.00,0.00,80.69,8.34,5.46,6.33,7790.0
1742,Indian Toners,523586.0,NaN,Dyes And Pigments,309.70,335.99,12.86,1.44,1.60,11.76,...,30.72,0.00,0.00,0.03,0.00,173.51,19.53,13.06,14.87,16558.0
1753,Indo Count Inds.,521016.0,ICIL,Textiles - Cotton/Blended,440.00,8714.41,25.80,0.47,4.18,10.20,...,28.40,10.69,-0.05,2.16,1.10,90.52,15.07,8.76,16.33,73384.0
1780,InfoBeans Tech.,543644.0,INFOBEAN,Computers - Software - Medium / Small,452.40,1102.44,49.06,0.22,3.72,5.54,...,25.72,0.29,0.00,0.01,0.00,111.97,19.11,8.96,14.32,28397.0
1945,JK Tyre & Indust,530007.0,JKTYRE,Tyres,442.20,11529.17,14.32,0.43,2.58,6.24,...,27.73,14.15,-1.14,4.99,-0.19,137.93,11.13,2.42,9.49,226143.0
1955,Joindre Capital,531861.0,NaN,Finance & Investments,51.00,70.58,46.43,2.45,0.98,1.06,...,36.32,0.00,0.00,0.00,0.00,51.85,6.56,2.52,4.35,3742.0
1966,JSW Steel,500228.0,JSWSTEEL,Steel - Large,943.20,230655.22,27.35,0.78,2.99,3.91,...,18.30,25.52,-0.54,10.52,0.71,271.78,8.33,1.84,5.64,671779.0
2024,Kamdhenu,532741.0,KAMDHENU,Steel - Medium / Small,521.50,1404.69,28.02,0.29,6.58,20.35,...,36.65,6.12,2.12,0.18,-0.01,61.96,23.22,12.25,20.94,17169.0
2157,Kovai Medical,523323.0,NaN,Healthcare,4289.75,4693.00,26.11,0.12,5.27,12.48,...,38.91,0.32,-0.02,4.28,0.10,657.12,16.79,8.44,17.67,11918.0
2303,M R P L,500109.0,MRPL,Refineries,215.55,37777.26,10.52,0.47,2.86,10.21,...,7.64,2.26,-0.42,1.50,0.00,56.29,20.13,7.08,31.22,440569.0
2326,Mafatlal Inds.,500264.0,NaN,Textiles - Composite,208.30,1496.71,15.15,0.00,1.86,1.70,...,28.75,0.71,-0.14,0.93,-0.01,86.89,5.25,1.70,3.13,60676.0
2328,Magadh Sugar,540650.0,MAGADSUGAR,Sugar,771.00,1086.45,9.31,0.90,1.46,7.71,...,38.55,0.43,-0.06,0.01,0.00,453.72,8.76,3.65,8.14,11180.0
2501,Minda Corp,538962.0,MINDACORP,Auto Ancillaries,487.50,11655.12,51.26,0.24,5.87,6.84,...,6.86,6.07,1.00,20.63,0.03,66.34,16.47,9.86,19.56,100689.0
2534,Modison,506261.0,MODISONLTD,Electric Equipment,124.25,403.19,23.40,0.80,1.97,7.00,...,47.40,0.48,0.07,0.00,0.00,57.65,10.24,5.91,7.09,19040.0
2556,Morganite Crucib,523160.0,NaN,Refractories / Intermediates,1510.00,845.60,32.86,1.83,6.60,15.35,...,24.32,0.13,0.13,0.55,0.53,226.70,17.84,10.17,12.88,6270.0
2609,N R Agarwal Inds,516082.0,NRAIL,Paper,505.20,859.80,6.86,0.00,1.13,9.62,...,25.56,0.46,0.05,0.01,0.00,373.48,21.55,9.79,17.09,9725.0
2918,Patels Airtemp,517417.0,NaN,Engineering,728.00,398.23,27.12,0.41,2.78,4.02,...,53.57,0.00,0.00,0.00,0.00,236.85,12.93,3.46,9.29,7195.0
2968,Pidilite Inds.,500331.0,PIDILITIND,Chemicals,3163.75,160911.28,90.35,0.35,19.14,15.92,...,9.71,11.59,0.28,8.97,0.04,141.89,23.83,12.89,18.70,541114.0
3370,S H Kelkar & Co.,539450.0,SHK,Chemicals,192.35,2662.50,21.70,1.04,2.20,5.37,...,32.27,8.71,-0.15,0.27,0.00,76.89,8.04,3.18,6.66,46379.0
3497,Saurashtra Cem.,502175.0,SAURASHCEM,Cement - North India,134.25,1489.97,21.45,0.74,1.63,4.74,...,32.73,0.01,0.01,0.37,0.00,125.35,-1.97,-1.55,-2.40,52990.0
3619,Shilchar Tech.,531201.0,NaN,Electric Equipment,5797.20,4421.41,48.12,0.09,21.09,39.08,...,32.37,3.08,-0.47,0.02,0.02,159.79,53.97,26.70,42.96,16011.0
3643,Shree Cement,500387.0,SHREECEM,Cement - North India,28214.80,101801.12,42.49,0.36,4.95,8.83,...,12.59,11.85,-0.62,12.78,0.64,5165.20,8.51,5.03,6.98,28268.0
3737,Siyaram Silk,503811.0,SIYSIL,Textiles - Processing,516.65,2344.05,12.70,2.12,2.06,11.38,...,28.47,1.53,-0.03,2.54,-0.39,243.42,28.12,15.73,23.88,39722.0
3766,Sobha,532784.0,SOBHA,Construction,1963.45,20999.84,427.64,0.15,8.34,0.37,...,17.24,10.93,-0.94,19.04,1.49,233.15,8.32,0.86,4.24,100295.0
3932,Sunshield Chem.,530845.0,NaN,Chemicals,1020.20,750.16,39.83,0.20,9.15,9.27,...,32.60,5.01,0.00,0.01,0.00,89.76,19.26,7.79,22.83,4617.0
4004,Swelect Energy,532051.0,SWELECTES,Electric Equipment,1265.00,1917.59,79.13,0.24,2.28,1.57,...,43.32,0.12,0.06,0.20,-0.27,519.32,4.16,0.13,0.21,23905.0
4041,TajGVK Hotels,532390.0,TAJGVK,Hotels,335.20,2101.79,28.24,0.00,3.86,9.40,...,21.49,0.82,0.12,2.69,-0.27,73.57,22.49,12.76,22.50,77579.0
4088,TD Power Systems,533553.0,TDPOWERSYS,Electric Equipment,353.45,5520.32,46.64,0.14,7.85,12.19,...,19.34,14.84,1.99,31.53,-0.83,38.74,22.06,10.59,16.93,68416.0
4130,Thermax,500411.0,THERMAX,Engineering,5323.80,63436.45,108.02,0.22,14.28,6.19,...,4.50,15.15,2.91,12.88,-2.94,324.62,15.06,5.57,12.31,40819.0
4152,Tinna Rubber,530475.0,NaN,Miscellaneous,1873.15,3208.61,79.64,0.16,25.11,17.49,...,26.22,0.79,0.05,0.00,0.00,56.13,23.57,11.08,24.39,21711.0
4223,Tube Investments,540762.0,TIINDIA,Steel - Large,4213.30,81491.91,98.54,0.08,15.97,10.14,...,11.61,27.40,-0.93,15.49,0.69,204.56,31.58,13.72,26.97,80778.0
4314,UTI AMC,543238.0,UTIAMC,Finance & Investments,1033.10,13149.27,17.19,2.15,2.99,16.86,...,33.08,6.27,0.30,60.67,-0.26,304.59,15.88,10.78,11.68,148066.0
4514,Weizmann,523011.0,WEIZMANIND,Textiles - Processing,134.80,213.79,23.84,0.37,2.95,9.01,...,32.13,0.00,0.00,0.00,0.00,40.82,12.34,4.10,6.61,9612.0
4554,WPIL,505872.0,NaN,Engineering - Turnkey Services,4436.00,4332.69,32.32,0.48,3.47,8.03,...,20.78,5.81,-0.01,2.62,0.00,82.89,24.33,10.99,26.25,12803.0

In [ ]:
# Load the two CSV files
ratio_file = "ratios_1.csv"  # Replace with the path to your first file
ratio_2_file = "ratios_1_T2.csv"  # Replace with the path to your second file
other_metrics = "other_metrics.csv"
other_metrics_2 = "other_metrics_T2.csv"


ratio_df = pd.read_csv(ratio_file)
ratio_2_df = pd.read_csv(ratio_2_file)
other_metrics_df = pd.read_csv(other_metrics)
other_metrics_2_df = pd.read_csv(other_metrics_2)

# Merge the two DataFrames on a common identifier, e.g., 'Stock'
# merged_data_1 = pd.merge(ratio_df, ratio_2_df, on='Name', suffixes=('_T1', '_T2'))
# merged_data= pd.merge(merged_data_1, other_metrics_df, other_metrics_2_df, on='Name', suffixes=('_T1', '_T2'))


# Merge the two DataFrames on a common identifier, e.g., 'Stock'
merged_data_1 = pd.merge(ratio_df, ratio_2_df, on='Name', suffixes=('_T1', '_T2'))
# Merge with other_metrics_df first
merged_data = pd.merge(merged_data_1, other_metrics_df, on='Name', suffixes=('_T3', '_T4'))
# Then merge with other_metrics_2_df, using the correct suffixes
merged_data = pd.merge(merged_data, other_metrics_2_df, on='Name', suffixes=('_T5', '_T6'))


# Filter rows where:
# 1. Price has reduced
# 2. PE, PBV, and Debt to Equity have decreased
filtered_data = merged_data[
    (merged_data['Price to Earning_T2'] < merged_data['Industry PE_T1']) &
    (merged_data['EVEBITDA_T5'] < merged_data['EVEBITDA_T6']) &
    (merged_data['Debt to equity_T2'] <= merged_data['Debt to equity_T1'])
]

# Save the filtered stocks to a new CSV file
output_file = "decreased_ratios_approach2.csv"
filtered_data.to_csv(output_file, index=False)

# Print the result and display the filtered rows
print(f"Filtered {len(filtered_data)} stocks where ratios decreased.")
display(filtered_data)

Filtered 894 stocks where ratios decreased.

,Name,BSE Code_T1,NSE Code_T1,Industry_T1,Current Price_T1,Market Capitalization_T1,Price to Earning_T1,Dividend yield_T1,Price to book value_T1,Return on assets_T1,...,Dividend Payout Ratio_T6,Graham_T6,Price to Cash Flow_T6,ROCE3yr avg_T6,PB X PE_T6,NCAVPS_T6,Market Capt to Cash Flow_T6,Altman Z Score_T6,Market cap to quarterly profit_T6,Market Capitalization_T6
0,20 Microns,533022.0,20MICRONS,Mining / Minerals / Metals,225.65,796.25,13.84,0.57,2.30,10.35,...,7.87,194.00,18.66,20.14,48.64,70.17,18.65,6.05,56.85,1015.37
3,3B Blackbio,532067.0,NaN,Healthcare,1184.50,1016.66,31.66,0.21,4.54,13.89,...,0.00,472.22,39.75,22.23,159.55,123.17,39.67,9.56,121.63,1069.10
10,63 Moons Tech.,526881.0,63MOONS,Computers - Software - Medium / Small,378.20,1742.67,8.31,0.52,0.53,5.90,...,4.14,888.42,39.43,2.25,4.96,342.47,39.41,2.95,486.60,1858.81
30,Aarey Drugs,524412.0,AAREYDRUGS,Pharmaceuticals - Indian - Bulk Drugs,45.65,115.88,24.77,0.00,0.87,1.57,...,0.00,46.58,-48.80,6.96,25.55,56.10,-48.77,3.20,58.53,125.83
36,Aarti Pharma,543748.0,AARTIPHARM,Pharmaceuticals - Indian - Bulk Drugs & Formln,608.00,5510.05,25.41,0.33,3.14,9.01,...,12.53,323.12,27.13,17.36,90.58,93.75,27.13,6.11,89.97,5870.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4590,Zee Learn,533287.0,ZEELEARN,Computers - Education,7.74,252.40,5.45,0.00,1.39,4.40,...,0.00,25.08,6.71,7.69,13.52,-0.33,6.71,1.34,8.32,338.81
4593,Zenith,NaN,ZENITHDRUG,Pharmaceuticals - Indian - Formulations,63.20,108.38,9.86,0.00,1.75,NaN,...,0.00,67.39,NaN,27.11,33.20,37.91,NaN,NaN,NaN,150.82
4595,Zenith Fibres,514266.0,NaN,Textiles - Manmade,85.00,33.53,25.40,1.77,0.60,2.25,...,29.85,102.47,33.56,6.11,15.52,94.33,33.94,3.61,197.65,33.60
4600,Zensar Tech.,504067.0,ZENSARTECH,Computers - Software - Medium / Small,757.30,17165.66,25.76,0.66,4.83,15.17,...,30.65,322.59,26.92,20.22,125.71,50.87,26.91,9.02,109.45,17281.44
4611,Zydus Lifesci.,532321.0,ZYDUSLIFE,Pharmaceuticals - Indian - Bulk Drugs & Formln,1067.35,107400.41,27.88,0.29,5.40,14.47,...,7.82,412.40,38.96,16.88,206.56,65.66,38.96,9.45,106.65,125769.19

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# Load the three CSV files
reduced_price_file = "stocks_with_increased_price.csv"  # Replace with the path to your reduced price file
increased_ratios_file = "increased_ratios_approach2.csv"       # Replace with the path to your increased ratios file
decreased_ratios_file = "decreased_ratios_approach2.csv"       # Replace with the path to your decreased ratios file

reduced_price_df = pd.read_csv(reduced_price_file)
increased_ratios_df = pd.read_csv(increased_ratios_file)
decreased_ratios_df = pd.read_csv(decreased_ratios_file)

# Merge the DataFrames on the 'Name' column (or 'Stock' depending on your data)
merged_data = reduced_price_df.merge(increased_ratios_df, on='Name', how='inner')
merged_data = merged_data.merge(decreased_ratios_df, on='Name', how='inner')

# Save the final filtered list to a new CSV file
output_file = "stocks_in_all_three_files.csv"
merged_data.to_csv(output_file, index=False)

# Print the result and display the filtered rows
print(f"Filtered {len(merged_data)} stocks that exist in all three files.")
display(merged_data)

Filtered 0 stocks that exist in all three files.

Empty DataFrame
Columns: [Name, BSE Code_T1_x, NSE Code_T1_x, Industry_T1_x, Current Price_T1_x, Return over 3months_T1, Return over 6months_T1, Volume 1month average_T1, Volume 1week average_T1, Volume_T1, High price_T1, Low price_T1, High price all time_T1, Low price all time_T1, Return over 1day_T1, Return over 1week_T1, Return over 1month_T1, DMA 50_T1, DMA 200_T1, DMA 50 previous day_T1, DMA 200 previous day_T1, RSI_T1, MACD_T1, MACD Previous Day_T1, MACD Signal_T1, MACD Signal Previous Day_T1, Return over 1year_T1, Return over 3years_T1, Return over 5years_T1, Volume 1year average_T1, Return over 7years_T1, Return over 10years_T1, Market Capitalization_T1_x, BSE Code_T2_x, NSE Code_T2_x, Industry_T2_x, Current Price_T2_x, Return over 3months_T2, Return over 6months_T2, Volume 1month average_T2, Volume 1week average_T2, Volume_T2, High price_T2, Low price_T2, High price all time_T2, Low price all time_T2, Return over 1day_T2, Return over 1week_T2, Return over 1month_T2, DMA 50_T2, DMA 200_T2, DMA 50 previous day_T2, DMA 200 previous day_T2, RSI_T2, MACD_T2, MACD Previous Day_T2, MACD Signal_T2, MACD Signal Previous Day_T2, Return over 1year_T2, Return over 3years_T2, Return over 5years_T2, Volume 1year average_T2, Return over 7years_T2, Return over 10years_T2, Market Capitalization_T2_x, BSE Code_T1_y, NSE Code_T1_y, Industry_T1_y, Current Price_T1_y, Market Capitalization_T1_y, Price to Earning_T1_x, Dividend yield_T1_x, Price to book value_T1_x, Return on assets_T1_x, Debt to equity_T1_x, Return on equity_T1_x, Promoter holding_T1_x, Earnings yield_T1_x, Pledged percentage_T1_x, Industry PE_T1_x, Enterprise Value_T1_x, Number of equity shares_T1_x, Book value_T1_x, Inventory turnover ratio_T1_x, Quick ratio_T1_x, Exports percentage_T1_x, Piotroski score_T1_x, G Factor_T1_x, Asset Turnover Ratio_T1_x, Financial leverage_T1_x, Number of Shareholders_T1_x, Unpledged promoter holding_T1_x, Return on invested capital_T1_x, Debtor days_T1_x, Industry PBV_T1_x, Credit rating_T1_x, Working Capital Days_T1_x, Earning Power_T1_x, Graham Number_T1_x, Cash Conversion Cycle_T1_x, ...]
Index: []

[0 rows x 257 columns]